### ISSUE TITLE
Align scroll direction between GNOME-panel and pop-up menu

### ISSUE THREAD

**Issue by domi413** [sakithb/media-controls#181] opened 2024-12-25 00:31 UTC
**Is your feature request related to a problem? Please describe.**  
When opening the pop-up menu, if the text is too long, it scrolls as expected. However, the scrolling direction in the GNOME panel moves from right to left, while in the pop-up menu it moves from left to right. This creates two issues:  

1. The opposite scrolling directions look inconsistent and somewhat distracting.
2. Scrolling from right to left in the pop-up menu would make more sense for most users, as many languages are read from left to right.

**Describe the solution you'd like**  
- Change the scrolling direction in the pop-up menu to match the GNOME panel.
- Alternatively, add a setting to configure the scrolling direction for both interfaces.  
- Ideally, ensure the scrolling direction is consistent across both the GNOME panel and the pop-up menu.

**Comment by ChrisLauinger77** [comment] 2024-12-25 07:48
duplicate of #165

**Closed** 2024-12-25 07:53 UTC
Labels: duplicate

**Comment by domi413** [comment] 2024-12-25 12:17
This is a great way to handle enhancements... If two people have already complained about this, I don’t understand why you’re not interested in making the effort to implement it. However, if I were to implement this feature to allow configuring the scrolling direction of each text, would you at least consider merging the pull request?

**Comment by ChrisLauinger77** [comment] 2024-12-25 15:23
I do not really feel this as an enhancement tbh - I even turned scrolling off as it distracts me.
They way is currently implemented was done on purpose (by sakithb, not me).
If you want it you can make a PR - sure. But please do not make more then one new parameter.
The rewrite of the extension cleaned also the parameters up - we should not get started in a new parameter mess ...
