### ISSUE TITLE
no shuffle symbol not showing

### ISSUE THREAD

**Issue by Sanjai-Shaarugesh** [sakithb/media-controls#172] opened 2024-11-21 16:28 UTC
**Describe the bug**
No shuffle icon not showing 

**To Reproduce**
1. Go to 'shell_only.ts' file
2. change   shuffle off  icon in gnome 47
4. See error  no shuffle symbol not showing error in fedora 41 change the  , change media-playlist-no-shuffle-symbolic to  media-playlist-consecutive-symbolic in SHUFFLE_OFF 

**Expected behaviour**
NO shuffle icon not showing in the medial controller when it switch back from shuffle  

change the icon name 

**Screenshots**
![Screenshot From 2024-11-21 21-55-11](https://github.com/user-attachments/assets/d2475591-1891-4aaf-a5fd-cc17f9ad4337)

**Environment:**
 - Fedora 41
 - GNOME version [47]
 - Extension Version [2.0.2] 

**Additional context**
`SHUFFLE_ON: {
        name: "shuffle",
        iconName: "media-playlist-shuffle-symbolic",
        menuProps: {
            index: 4,
            options: {
                xExpand: false,
                xAlign: Clutter.ActorAlign.END,
            },
        },
    },
    SHUFFLE_OFF: {
        name: "shuffle",
        iconName: "media-playlist-consecutive-symbolic",
        menuProps: {
            index: 4,
            options: {
                xExpand: false,
                xAlign: Clutter.ActorAlign.END,
            },
        },
    },
};`
## **to** 
***this***

`SHUFFLE_ON: {
        name: "shuffle",
        iconName: "media-playlist-consecutive-symbolic",
        menuProps: {
            index: 4,
            options: {
                xExpand: false,
                xAlign: Clutter.ActorAlign.END,
            },
        },
    },
    SHUFFLE_OFF: {
        name: "shuffle",
        iconName: "media-playlist-shuffle-symbolic",
        menuProps: {
            index: 4,
            options: {
                xExpand: false,
                xAlign: Clutter.ActorAlign.END,
            },
        },
    },
};`
## to fixes the bug 
**and it will work**

![Screenshot From 2024-11-21 22-07-26](https://github.com/user-attachments/assets/c7ec63f5-130f-4ce0-930f-a840e3a80956)

**Comment by ssrublev** [comment] 2024-11-21 16:30
The people here are greatly ignorant to your reports. They will close it briefly. They are not willing to talk to anyone. Why are you writing this here?

**Comment by ChrisLauinger77** [comment] 2024-11-21 16:36
A little strange description - but I can reproduce it. The shuffle button in the popup menu does not show an icon when clicked. Also not when the default icon theme of gnome is used. I will look into it

**Comment by ChrisLauinger77** [comment] 2024-11-21 16:36
> The people here are greatly ignorant to your reports. They will close it briefly. They are not willing to talk to anyone. Why are you writing this here?

What ?

**Comment by ssrublev** [comment] 2024-11-21 17:15
> > The people here are greatly ignorant to your reports. They will close it briefly. They are not willing to talk to anyone. Why are you writing this here?
> 
> What ?

Any bugs filled here momentally receive reply "closed as not planned" like here and everywhere https://github.com/sakithb/media-controls/issues/165

while GNOME is very buggy and leaking

**Comment by ChrisLauinger77** [comment] 2024-11-21 17:27
> > > The people here are greatly ignorant to your reports. They will close it briefly. They are not willing to talk to anyone. Why are you writing this here?
> > 
> > 
> > What ?
> 
> Any bugs filled here momentally receive reply "closed as not planned" like here and everywhere #165
> 
> while GNOME is very buggy and leaking

#165 is not a bug - it is intentionally implemented like this - I already commented on it

**Closed** 2024-11-22 12:50 UTC
Labels: bug
